version: "3.3"

services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - local_settings.env
    ports:
      - '54321:5432'
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: